USE [master]
GO

/****** Object:  Database [ProxyDB]    Script Date: 11/12/2015 00:51:14 ******/
CREATE DATABASE [ProxyDB] ON  PRIMARY 
( NAME = N'ProxyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\ProxyDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProxyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\ProxyDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProxyDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProxyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProxyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProxyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProxyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProxyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProxyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProxyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProxyDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ProxyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProxyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProxyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProxyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProxyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProxyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProxyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProxyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProxyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProxyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProxyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProxyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProxyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProxyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProxyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProxyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProxyDB] SET  READ_WRITE 
GO

ALTER DATABASE [ProxyDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ProxyDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProxyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProxyDB] SET DB_CHAINING OFF 
GO


